# [[https://melpa.org/#/burnish][file:https://melpa.org/packages/burnish-badge.svg]] [[https://stable.melpa.org/#/burnish][file:https://stable.melpa.org/packages/burnish-badge.svg]]

* Burnish
THIS PROJECT IS WIP.

*Burnish* is an Elisp package that automates the export and viewing of an [[https://orgmode.org/][Org file]]. With *Burnish*, users can rapidly iterate and review changes to an Org file.


* Features

- Automated export and view support for the following [[https://www.gnu.org/software/emacs/manual/html_mono/org.html#Exporting][Org backends]]:

  - HTML
  - Markdown
  - ODT
  - Texinfo/Info
  - LaTeX PDF

- Trigger export and view via ~save-buffer~ or by a customizable key binding (default ~C-<f5>~).

- Support for additional export backends.

  *Burnish* provides a high-degree of customization to support different export and view behaviors for both built-in and user-added backends.

- File-level control of running *Burnish*.

  Only automate export and view on the files you specify.

* Requirements

- [[https://www.gnu.org/software/emacs/][GNU Emacs]] 30.1+

* Install

If manually installed, ensure that ~burnish.el~ is in your ~load-path~.

*Burnish* is intended to be run as a minor mode (~burnish-mode~) to Org mode. It can be added as a hook to ~org-mode-hook~. This will always enable ~burnish-mode~ whenever an Org file is loaded.

#+begin_src elisp :lexical no
  (add-hook 'org-mode-hook #'burnish-mode)
#+end_src

Alternately ~burnish-mode~ can be invoked in an Org buffer as desired:

#+begin_src elisp :lexical no
  M-x burnish-mode RET
#+end_src

With ~burnish-mode~, automated export of an Org file and viewing the result is done on every file save. If this behavior is not desired, then an alternate install is to bind the command ~burnish~.

#+begin_src elisp :lexical no
  (keymap-set org-mode-map burnish-export-key #'burnish)
#+end_src

~burnish-export-key~ is a customizable variable whose default value is ~C-<f5>~.

  
* Usage

When the minor mode ~burnish-mode~ is enabled, automated export of an Org file and viewing the result is performed on every save (~save-buffer~) of said file. However, automated export and view only works when the local file variable ~burnish-backend~ is defined in the Org file as detailed in [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Specifying-File-Variables.html][Specifying File Variables (GNU Emacs Manual)]]. If ~burnish-backend~ is not defined in an Org file, nothing will be done by *Burnish* on said file.

An example of setting ~burnish-backend~ is shown below, where the text is appended at the end of the file.

#+begin_example
# Local Variables:
# burnish-backend: html
# End:
#+end_example

Rather than typing the above in an Org file, the command ~burnish-select-backend~ will insert this for you, prompting for an export backend with completion support.

To directly export an Org file and view the result, invoke the command ~burnish~ by its key binding (default: ~C-<f5>~) or by direct invocation (~M-x~)

Refer to the [[https://kickingvegas.github.io/burnish/][Burnish User Guide]] for more details on using and customizing it.

* Sponsorship

If you enjoy using *Burnish*, please consider buying me a coffee to help support its development and maintenance.

[[https://www.buymeacoffee.com/kickingvegas][http://yummymelon.com/devnull/theme/images/icons/buymecoffee.png]]

  
* Acknowledgments

Thanks goes out to the contributors of Org Mode and GNU Emacs, whose work this builds upon. This work would not be possible without your efforts.

