# [[https://melpa.org/#/burnish][file:https://melpa.org/packages/burnish-badge.svg]] [[https://stable.melpa.org/#/burnish][file:https://stable.melpa.org/packages/burnish-badge.svg]]

* Burnish
THIS PROJECT IS WIP.

*Burnish* is an Elisp package that automates the export and viewing of an [[https://orgmode.org/][Org file]]. With *Burnish*, users can rapidly iterate and review changes to an Org file.


* Features

- Automated export and view support for the following [[https://www.gnu.org/software/emacs/manual/html_mono/org.html#Exporting][Org backends]]:

  - HTML
  - Markdown
  - ODT
  - Texinfo/Info
  - LaTeX PDF

- Trigger export and view via ~save-buffer~ or by a customizable key binding (default ~C-<f5>~).

- Support for additional export backends.

  *Burnish* provides a high-degree of customization to support different export and view behaviors for both built-in and added backends.

- File-level control of running *Burnish*.

  Only automate export and view on the files you specify.

* Requirements

- [[https://www.gnu.org/software/emacs/][GNU Emacs]] 30.1+

* Install

If manually installed, ensure that ~burnish.el~ is in your ~load-path~.

*Burnish* is intended to be run as a minor mode (~burnish-mode~) to Org mode. It can be added as a hook to ~org-mode-hook~. This will always enable ~burnish-mode~ whenever an Org file is loaded.

#+begin_src elisp :lexical no
  (add-hook 'org-mode-hook #'burnish-mode)
#+end_src

Alternately ~burnish-mode~ can be invoked in an Org buffer as desired:

#+begin_src elisp :lexical no
  M-x burnish-mode RET
#+end_src

With ~burnish-mode~, automated export of an Org file and viewing the result is done on every file save. If this behavior is not desired, then an alternate install is to bind the command ~burnish~.

#+begin_src elisp :lexical no
  (keymap-set org-mode-map burnish-export-key #'burnish)
#+end_src

~burnish-export-key~ is a customizable variable whose default value is ~C-<f5>~.

~burnish-bind~ will do the following:

- Add the command ~burnish~ to the hook variable ~after-save-hook~.
- Bind the command ~burnish~ to the key set in the variable ~burnish-export-key~ (default ~C-<f5>~).
  
* Usage

Refer to the [[https://kickingvegas.github.io/burnish/][Burnish User Guide]] for guidance.

* Sponsorship

If you enjoy using *Burnish*, please consider buying me a coffee to help support its development and maintenance.

[[https://www.buymeacoffee.com/kickingvegas][http://yummymelon.com/devnull/theme/images/icons/buymecoffee.png]]

  
* Acknowledgments

Thanks goes out to the contributors of Org Mode and GNU Emacs, whose work this builds upon. This work would not be possible without your efforts. 


