\input texinfo    @c -*- texinfo -*-
@c %**start of header
@setfilename burnish.info
@settitle Burnish User Guide
@documentencoding UTF-8
@documentlanguage en
@syncodeindex pg cp
@paragraphindent none
@c %**end of header

@copying
Copyright © 2026 Charles Y@. Choi
@end copying

@dircategory Emacs misc features
@direntry
* Burnish: (burnish).   Automate Org file export and view.
@end direntry

@finalout
@titlepage
@title Burnish User Guide
@subtitle for version 0.0.1-rc.1
@author Charles Y@. Choi (@email{kickingvegas@@gmail.com})
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@top Burnish User Guide

Version: 0.0.1-rc.1

Copyright © 2026 @w{Charles Y. Choi}

THIS DOCUMENT IS WIP@.

@strong{Burnish} is an Elisp package to automate the export and viewing of an Org file (@ref{Top,,,org,}). With @strong{Burnish}@comma{} users can rapidly iterate and review changes to their Org document.


If you enjoy using @strong{Burnish}@comma{} please consider buying me a coffee to help support its development and maintenance.

@uref{https://www.buymeacoffee.com/kickingvegas}

@end ifnottex

@menu
* Features::
* Requirements::
* Install::
* Usage::
* Feedback & Discussion::
* Sponsorship::
* About::
* Acknowledgments::
* Main Index::
* Variable Index::

@detailmenu
--- The Detailed Node Listing ---

Usage

* Commands::
* Customization::

@end detailmenu
@end menu

@node Features
@chapter Features

@cindex Features


@itemize
@item
Automated export and view support for the following Org backends:
@itemize
@item
HTML
@item
Markdown
@item
ODT
@item
Texinfo
@item
@LaTeX{} PDF
@end itemize

@item
Export and view can be triggered via @code{save-buffer} or by a customizable key binding (default @code{C-<f5>}).

@item
Support for additional export formats can be done with customizable variables.

@item
Control @strong{Burnish} operation on a per Org file basis.
@end itemize

@node Requirements
@chapter Requirements

@cindex Requirements

@itemize
@item
@uref{https://www.gnu.org/software/emacs/, GNU Emacs} 30.1+
@end itemize

@node Install
@chapter Install

@cindex Install

If manually installed@comma{} ensure that @code{burnish.el} is in your @code{load-path}.

Add the following to your Emacs initialization file.

@lisp
(require 'burnish) ; optional if autoloaded
(burnish-bind)
@end lisp

@code{burnish-bind} will do the following:

@itemize
@item
Add the command @code{burnish} to the hook variable @code{after-save-hook}.
@item
Bind the command @code{burnish} to the key set in the variable @code{burnish-export-key} (default @code{C-<f5>}).
@end itemize

@node Usage
@chapter Usage

For @strong{Burnish} to work@comma{} it requires that the local file variable @code{burnish-backend} be defined in the Org file. The value of this variable is set to a target Org backend. By default@comma{}  @code{burnish-backend} supports the following values:

@itemize
@item
html — export to HTML
@item
md — export to Markdown
@item
odt — export to Open Office Doc
@item
latex — export to @LaTeX{}
@item
texinfo — export to Texinfo
@end itemize

An example of defining @code{burnish-backend} in an Org file is shown below@comma{} where this text is appended at the end of the file. For more detail on file variables@comma{} see @ref{Specifying File Variables,,,emacs,}.

@example

@end example

To set @code{burnish-backend} as a local variable@comma{} either load the file or revert it using @code{revert-buffer}. Any subsequent changes to the Org file will trigger an automatic export and view of the output.

@menu
* Commands::
* Customization::
@end menu

@node Commands
@section Commands

@vindex burnish
@deffn Command burnish
Run the function that exports and views the Org file.

This function is specified by two variables:

@itemize
@item
@code{burnish-export-functions} — map containing (backend@comma{} export function) pairs.

@item
@code{burnish-backend} — local file variable specifying with backend to use.
@end itemize
@end deffn

@vindex burnish-bind
@deffn Command burnish-bind
Turn on automatic export and viewing of an Org file.

For an Org file that has the local file variable @code{burnish-backend} specified@comma{}

Configure Emacs to run @code{burnish} whenever an Org file with @code{burnish-backend} defined is saved.

This command also binds @code{burnish} to the key sequence specified by @code{burnish-export-key}.
@end deffn

@vindex burnish-unbind
@deffn Command burnish-unbind
Turn off automatic export and viewing of an Org file.

This command undoes all configuration done by @code{burnish-bind}.
@end deffn

@vindex burnish-select-backend
@deffn Command burnish-select-backend CHOICE
Set local variable ‘burnish-backend’ to CHOICE in Org file.

This command modifies the Org file to set the local file variable @code{burnish-backend} within it.

See @ref{Specifying File Variables,,,emacs,} for more detail on local file variables.

When run interactively@comma{} @code{burnish-select-backend} prompts the user for a backend (CHOICE) to use when exporting and viewing an Org file. The prompt supports completion whose choices are the backend keys defined in the customizable variable @code{burnish-export-functions}.
@end deffn

@node Customization
@section Customization

@cindex Customization

@defvar burnish-backend
Local file variable that must be set in an Org file for the @code{burnish} command to run.
@end defvar

@defopt @code{burnish-export-functions}
Alist of export backends and their corresponding functions.

Each element is a cons cell (SYMBOL . FUNCTION) where SYMBOL is an export backend and FUNCTION is its corresponding export function.

This variable can be amended to support additional export backends provided that an export function for the new backend is defined.
@end defopt

@defopt burnish-export-key
String used to define the key sequence to bind the command @code{burnish}. Default value @kbd{C-<f5>}.
@end defopt

@node Feedback & Discussion
@chapter Feedback & Discussion

@cindex Feedback
Please report any feedback about @strong{Burnish} to the @uref{https://github.com/kickingvegas/burnish/issues, issue tracker on GitHub}.

@cindex Discussion
To participate in general discussion about using @strong{Burnish}@comma{} please join the @uref{https://github.com/kickingvegas/burnish/discussions, discussion group}.

@node Sponsorship
@chapter Sponsorship

@cindex Sponsorship

If you enjoy using @strong{Burnish}@comma{} please consider buying me a coffee to help support its development and maintenance.

@uref{https://www.buymeacoffee.com/kickingvegas}

@node About
@chapter About

@cindex About

@uref{https://github.com/kickingvegas/burnish, Burnish} was conceived and crafted by Charles Y@. Choi in San Francisco@comma{} California.

Thank you for using @strong{Burnish}.

Always choose love.

@node Acknowledgments
@chapter Acknowledgments

@cindex Acknowledgments

@node Main Index
@chapter Main Index

Index for this user guide.

@printindex cp

@node Variable Index
@chapter Variable Index

Variables@comma{} functions@comma{} commands@comma{} and menus referenced by this user guide.

@printindex vr

@bye
