#+startup: overview nologdone
#+startup: showeverything
#+TITLE: Burnish User Guide
#+SUBTITLE: for version {{{version}}}
#+AUTHOR: Charles Y. Choi
#+EMAIL: kickingvegas@gmail.com
#+OPTIONS: ':t toc:t author:t email:t H:4 f:t
#+LANGUAGE: en
#+MACRO: version 0.0.1-rc.3
#+MACRO: kbd (eval (org-texinfo-kbd-macro $1))
#+TEXINFO_FILENAME: burnish.info
#+TEXINFO_CLASS: casual
#+TEXINFO_HEADER: @syncodeindex pg cp
#+TEXINFO_HEADER: @paragraphindent none
#+TEXINFO_TITLEPAGE: t
#+TEXINFO_DIR_CATEGORY: Emacs misc features
#+TEXINFO_DIR_NAME: Burnish
#+TEXINFO_DIR_DESC: Automate Org file export and view.
#+TEXINFO_PRINTED_TITLE: Burnish User Guide

Version: {{{version}}}

#+TEXINFO: Copyright © 2026 @w{Charles Y. Choi}

THIS DOCUMENT IS WIP.

*Burnish* is an Elisp package that automates the export and viewing of an Org file ([[info:org#Top]]). With *Burnish*, users can rapidly iterate and review changes to an Org file.

#+INCLUDE: "./sponsorship.org"

* Copying
:PROPERTIES:
:COPYING: t
:END:

Copyright © 2026 Charles Y. Choi

* Features
:PROPERTIES:
:CUSTOM_ID: features
:END:
#+CINDEX: Features

- Automated export and view support for the following Org backends ([[info:org#Exporting]]):

  - HTML
  - Markdown
  - ODT
  - Texinfo/Info
  - LaTeX PDF

- Trigger export and view via ~save-buffer~ or by a customizable key binding (default {{{kbd(C-<f5>)}}}).

- Support for additional export backends.

  *Burnish* provides a high-degree of customization to support different export and view behaviors for both built-in and added backends.

- File-level control of running *Burnish*.

  Only automate export and view on the files you specify.


* Requirements
:PROPERTIES:
:CUSTOM_ID: requirements
:END:
#+CINDEX: Requirements

- [[https://www.gnu.org/software/emacs/][GNU Emacs]] 30.1+


* Install
:PROPERTIES:
:CUSTOM_ID: install
:END:
#+CINDEX: Install

If manually installed, ensure that ~burnish.el~ is in your ~load-path~.

*Burnish* is intended to be run as a minor mode (~burnish-mode~) to Org mode. It can be added as a hook to ~org-mode-hook~. This will always enable ~burnish-mode~ whenever an Org file is loaded.

#+begin_src elisp :lexical no
  (add-hook 'org-mode-hook #'burnish-mode)
#+end_src

Alternately ~burnish-mode~ can be invoked in an Org buffer as desired:

#+begin_src elisp :lexical no
  M-x burnish-mode RET
#+end_src

With ~burnish-mode~, automated export of an Org file and viewing the result is done on every file save. If this behavior is not desired, then an alternate install is to bind the command ~burnish~.

#+begin_src elisp :lexical no
  (keymap-set org-mode-map burnish-export-key #'burnish)
#+end_src

~burnish-export-key~ is a customizable variable whose default value is {{{kbd(C-<f5>)}}}.

* Usage

When the minor mode ~burnish-mode~ is enabled, automated export of an Org file and viewing the result is performed on every save (~save-buffer~) of said file. However, automated export and view only works when the local file variable ~burnish-backend~ is defined in the Org file as detailed in [[info:emacs#Specifying File Variables]]. If ~burnish-backend~ is not defined in an Org file, nothing will be done by *Burnish* on said file.

An example of setting ~burnish-backend~ is shown below, where the text is appended at the end of the file.

#+begin_example
# Local Variables:
# burnish-backend: html
# End:
#+end_example

Rather than typing the above in an Org file, the command ~burnish-select-backend~ will insert this for you, prompting for an export backend with completion support.

To directly export an Org file and view the result, invoke the command ~burnish~ by its key binding (default: {{{kbd(C-<f5>)}}}) or by direct invocation ({{{kbd(M-x)}}}).

Details on commands and customization of *Burnish* can be found in the menu sections below.

# To set ~burnish-backend~ as a local variable, either load the file or revert it using ~revert-buffer~. Any subsequent changes to the Org file will trigger an automatic export and view of the output.


** Commands

#+VINDEX: burnish
- Command: burnish ::
  Run the function that exports the Org file and views the result as specified by ~burnish-backend~.

  This function is governed by two variables:

  - ~burnish-backend~ — local file variable specifying which export backend to use.

  - ~burnish-export-functions~ — alist map whose pairs are (SYMBOL FUNCTION), where SYMBOL is a backend key and FUNCTION is its corresponding export function.


#+VINDEX: burnish-select-backend
- Command: burnish-select-backend CHOICE ::
  Prompt the user for CHOICE and set the local file variable ~burnish-backend~ to it in an Org file.

  The prompt supports completion where choices are taken from the keys defined in ~burnish-export-functions~.
  
  This command will either add or update ~burnish-backend~ as detailed in [[info:emacs#Specifying File Variables]].


#+VINDEX: burnish-mode
- Command: burnish-mode ::
  Minor mode to enable automated Org file export and viewing of the result.

  When ~burnish-mode~ is enabled:
  - Automated export and view is triggered by a file save (~save-buffer~).
  - The key sequence ~burnish-export-key~ is bound to the command ~burnish~.

  Disabling ~burnish-mode~ undoes the above.

  
** Customization
#+CINDEX: Customization

- Variable: burnish-backend ::
  Local file variable that must be set in an Org file for the ~burnish~ command to run.

  It is recommended to use the command ~burnish-select-backend~ to edit this variable in an Org file.

  The values supported by ~burnish-backend~ are the keys of the alist ~burnish-export-functions~. By default these keys are:
  
  - html — export to HTML
  - md — export to Markdown
  - odt — export to Open Office Doc
  - info — export to Info via Texinfo
  - latex-pdf — export to LaTeX
  
- User Option: burnish-export-functions ::
  Alist of export backends and their corresponding functions.

  Each element is a cons cell (SYMBOL . FUNCTION) where SYMBOL is an export backend and FUNCTION is its corresponding export function.

  This customizable variable can be amended to support additional export backends provided that an export function for the new backend is defined. Similarly, an existing export function can be overridden with a user-defined export function.

- User Option: burnish-export-key ::
  Key sequence to bind the command ~burnish~. Default value {{{kbd(C-<f5>)}}}.

* Feedback & Discussion
#+CINDEX: Feedback
Please report any feedback about *Burnish* to the [[https://github.com/kickingvegas/burnish/issues][issue tracker on GitHub]].

#+CINDEX: Discussion
To participate in general discussion about using *Burnish*, please join the [[https://github.com/kickingvegas/burnish/discussions][discussion group]].

* Sponsorship
#+CINDEX: Sponsorship

#+INCLUDE: "./sponsorship.org"


* About
#+CINDEX: About

[[https://github.com/kickingvegas/burnish][Burnish]] was conceived and crafted by Charles Y. Choi in San Francisco, California.

Thank you for using *Burnish*.

Always choose love.

* Acknowledgments
#+CINDEX: Acknowledgments

Thanks goes out to the contributors of Org Mode and GNU Emacs, whose work this builds upon. This work would not be possible without your efforts. 

* Main Index
:PROPERTIES:
:INDEX:    cp
:END:

Index for this user guide.

* Variable Index
:PROPERTIES:
:INDEX:    vr
:END:

Variables, functions, commands, and menus referenced by this user guide.

  # Local Variables:
  # burnish-backend: kvtexinfo
  # End:
