\input texinfo    @c -*- texinfo -*-
@c %**start of header
@setfilename burnish.info
@settitle Burnish User Guide
@documentencoding UTF-8
@documentlanguage en
@syncodeindex pg cp
@paragraphindent none
@c %**end of header

@copying
Copyright © 2026 Charles Y@. Choi
@end copying

@dircategory Emacs misc features
@direntry
* Burnish: (burnish).   Automate Org file export and view.
@end direntry

@finalout
@titlepage
@title Burnish User Guide
@subtitle for version 0.0.1-rc.3
@author Charles Y@. Choi (@email{kickingvegas@@gmail.com})
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@top Burnish User Guide

Version: 0.0.1-rc.3

Copyright © 2026 @w{Charles Y. Choi}

THIS DOCUMENT IS WIP@.

@strong{Burnish} is an Elisp package that automates the export and viewing of an Org file (@ref{Top,,,org,}). With @strong{Burnish}@comma{} users can rapidly iterate and review changes to an Org file.

If you enjoy using @strong{Burnish}@comma{} please consider buying me a coffee to help support its development and maintenance.

@uref{https://www.buymeacoffee.com/kickingvegas}

@end ifnottex

@menu
* Features::
* Requirements::
* Install::
* Usage::
* Feedback & Discussion::
* Sponsorship::
* About::
* Acknowledgments::
* Main Index::
* Variable Index::

@detailmenu
--- The Detailed Node Listing ---

Usage

* Commands::
* Customization::

@end detailmenu
@end menu

@node Features
@chapter Features

@cindex Features

@itemize
@item
Automated export and view support for the following Org backends (@ref{Exporting,,,org,}):

@itemize
@item
HTML
@item
Markdown
@item
ODT
@item
Texinfo/Info
@item
@LaTeX{} PDF
@end itemize

@item
Trigger export and view via @code{save-buffer} or by a customizable key binding (default @kbd{C-<f5>}).

@item
Support for additional export backends.

@strong{Burnish} provides a high-degree of customization to support different export and view behaviors for both built-in and user-added backends.

@item
File-level control of running @strong{Burnish}.

Only automate export and view on the files you specify.
@end itemize

@node Requirements
@chapter Requirements

@cindex Requirements

@itemize
@item
@uref{https://www.gnu.org/software/emacs/, GNU Emacs} 30.1+
@end itemize

@node Install
@chapter Install

@cindex Install

If manually installed@comma{} ensure that @code{burnish.el} is in your @code{load-path}.

@strong{Burnish} is intended to be run as a minor mode (@code{burnish-mode}) to Org mode. It can be added as a hook to @code{org-mode-hook}. This will always enable @code{burnish-mode} whenever an Org file is loaded.

@lisp
(add-hook 'org-mode-hook #'burnish-mode)
@end lisp

Alternately @code{burnish-mode} can be invoked in an Org buffer as desired:

@lisp
M-x burnish-mode RET
@end lisp

With @code{burnish-mode}@comma{} automated export of an Org file and viewing the result is done on every file save. If this behavior is not desired@comma{} then an alternate install is to bind the command @code{burnish}.

@lisp
(keymap-set org-mode-map burnish-export-key #'burnish)
@end lisp

@code{burnish-export-key} is a customizable variable whose default value is @kbd{C-<f5>}.

@node Usage
@chapter Usage

When the minor mode @code{burnish-mode} is enabled@comma{} automated export of an Org file and viewing the result is performed on every save (@code{save-buffer}) of said file. However@comma{} automated export and view only works when the local file variable @code{burnish-backend} is defined in the Org file as detailed in @ref{Specifying File Variables,,,emacs,}. If @code{burnish-backend} is not defined in an Org file@comma{} nothing will be done by @strong{Burnish} on said file.

An example of setting @code{burnish-backend} is shown below@comma{} where the text is appended at the end of the file.

@example
# Local Variables:
# burnish-backend: html
# End:
@end example

Rather than typing the above in an Org file@comma{} the command @code{burnish-select-backend} will insert this for you@comma{} prompting for an export backend with completion support.

To directly export an Org file and view the result@comma{} invoke the command @code{burnish} by its key binding (default: @kbd{C-<f5>}) or by direct invocation (@kbd{M-x}).

Details on commands and customization of @strong{Burnish} can be found in the menu sections below.

@menu
* Commands::
* Customization::
@end menu

@node Commands
@section Commands

@vindex burnish
@deffn Command burnish
Run the function that exports the Org file and views the result as specified by @code{burnish-backend}.

This function is governed by two variables:

@itemize
@item
@code{burnish-backend} — local file variable specifying which export backend to use.

@item
@code{burnish-export-functions} — alist map whose pairs are (SYMBOL FUNCTION)@comma{} where SYMBOL is a backend key and FUNCTION is its corresponding export function.
@end itemize
@end deffn

@vindex burnish-select-backend
@deffn Command burnish-select-backend CHOICE
Prompt the user for CHOICE and set the local file variable @code{burnish-backend} to it in an Org file.

The prompt supports completion where choices are taken from the keys defined in @code{burnish-export-functions}.

This command will either add or update @code{burnish-backend} as detailed in @ref{Specifying File Variables,,,emacs,}.
@end deffn

@vindex burnish-mode
@deffn Command burnish-mode
Minor mode to enable automated Org file export and viewing of the result.

When @code{burnish-mode} is enabled:
@itemize
@item
Automated export and view is triggered by a file save (@code{save-buffer}).
@item
The key sequence @code{burnish-export-key} is bound to the command @code{burnish}.
@end itemize

Disabling @code{burnish-mode} undoes the above.
@end deffn

@node Customization
@section Customization

@cindex Customization

@defvar burnish-backend
Local file variable that must be set in an Org file for the @code{burnish} command to run.

It is recommended to use the command @code{burnish-select-backend} to edit this variable in an Org file.

The values supported by @code{burnish-backend} are the keys of the alist @code{burnish-export-functions}. By default these keys are:

@itemize
@item
html — export to HTML
@item
md — export to Markdown
@item
odt — export to Open Office Doc
@item
info — export to Info via Texinfo
@item
latex-pdf — export to @LaTeX{}
@end itemize
@end defvar

@defopt burnish-export-functions
Alist of export backends and their corresponding functions.

Each element is a cons cell (SYMBOL . FUNCTION) where SYMBOL is an export backend and FUNCTION is its corresponding export function.

This customizable variable can be amended to support additional export backends provided that an export function for the new backend is defined. Similarly@comma{} an existing export function can be overridden with a user-defined export function.
@end defopt

@defopt burnish-export-key
Key sequence to bind the command @code{burnish}. Default value @kbd{C-<f5>}.
@end defopt

@node Feedback & Discussion
@chapter Feedback & Discussion

@cindex Feedback
Please report any feedback about @strong{Burnish} to the @uref{https://github.com/kickingvegas/burnish/issues, issue tracker on GitHub}.

@cindex Discussion
To participate in general discussion about using @strong{Burnish}@comma{} please join the @uref{https://github.com/kickingvegas/burnish/discussions, discussion group}.

@node Sponsorship
@chapter Sponsorship

@cindex Sponsorship

If you enjoy using @strong{Burnish}@comma{} please consider buying me a coffee to help support its development and maintenance.

@uref{https://www.buymeacoffee.com/kickingvegas}

@node About
@chapter About

@cindex About

@uref{https://github.com/kickingvegas/burnish, Burnish} was conceived and crafted by Charles Y@. Choi in San Francisco@comma{} California.

Thank you for using @strong{Burnish}.

Always choose love.

@node Acknowledgments
@chapter Acknowledgments

@cindex Acknowledgments

Thanks goes out to the contributors of Org Mode and GNU Emacs@comma{} whose work this builds upon. This work would not be possible without your efforts.

@node Main Index
@chapter Main Index

Index for this user guide.

@printindex cp

@node Variable Index
@chapter Variable Index

Variables@comma{} functions@comma{} commands@comma{} and menus referenced by this user guide.

@printindex vr

@bye
